name: tests
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: cmake -P test_parse_file_options.cmake
      - run: cmake -P test_fetch_source_files.cmake
      - run: cmake -P test_fetch_source_groups.cmake
